ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
plugins=(git, zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh

source ~/.aliases

# Setup zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=5'

export PATH="/usr/local/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting